

server:
  port: 8080

spring:
  application:
    name:  ms-listen
routes:
  whatsappPostTestRoute: "https://graph.facebook.com/v23.0/690964500775870/messages"
token:
  security: "whatsappmessage"
  acess: "EAAfpPIDAZCEsBPFEpbKqZAOwoLppQWBroxWkaZCAcZAJdPEFfHYwkjN3ZAJLiCBbr9raP1OWRFdqGxTHCdjZAJQMYefEcX8IG5ZAdxHpOJ7DV3mjFSeTZCHaGTPU2yYZCVIil0PFImiBFCj8MCxppRZBvJ6O32wdimaoeSQyZA7WNnaTmPbb2y7zeeFxISD4sIfOxhdki8kHrX32RacEXHP4jtMv9rDbIgC1nN9KZCMdta0JjqqdVGnm"

